services:
  db:
    image: postgres:15
    container_name: fin-analytica-db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: fin-analytica
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  db_data:
    name: fin-analytica-data



  